name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# ðŸ”‘ REQUIRED PERMISSIONS
permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Pacman graph
        uses: Platane/snk@v3
        with:
          github_user_name: rana-rohit
          outputs: |
            output/pacman-contribution-graph.svg
            output/pacman-contribution-graph-dark.svg

      - name: Commit & push files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate pacman contribution graph"
          add: "output"
